### ISSUE TITLE
Traceback, maybe about components?

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/outlinerRoboFontExtension#11]
```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 90, in sendEvent_
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/vanilla/vanillaBase.py", line 539, in action_
    self.callback(sender)
  File "outline.py", line 345, in outlineButtonCallback
  File "outline.py", line 57, in calculate
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/objects/glyph.py", line 267, in _get_bounds
    return self._getContourComponentBounds("bounds")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/objects/glyph.py", line 258, in _getContourComponentBounds
    b = getattr(subObject, attr)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/objects/component.py", line 124, in _get_bounds
    return self.getRepresentation("defcon.component.bounds")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/objects/base.py", line 347, in getRepresentation
    return factory["factory"](self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/tools/representations.py", line 92, in componentBoundsRepresentationFactory
    obj.draw(pen)
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/objects/component.py", line 176, in draw
    self.drawPoints(pointPen)
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/defcon/objects/component.py", line 185, in drawPoints
    pointPen.addComponent(self._baseGlyph, self._transformation)
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/fontTools/pens/pointPen.py", line 265, in addComponent
    self.pen.addComponent(glyphName, transform)
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.12/fontTools/pens/basePen.py", line 238, in addComponent
    glyph = self.glyphSet[glyphName]
            ~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

Upon clicking the button, with these settings:
<img width="400" alt="image" src="https://github.com/typemytype/outlinerRoboFontExtension/assets/12752088/b6b19e85-9986-42ce-aa43-1088541fb714">

**Comment by typemytype** [comment]
yeah any component... looking at it

**Comment by typemytype** [comment]
update to Outliner 2.5
fixed in https://github.com/typemytype/outlinerRoboFontExtension/commit/311ab4852824180686331713216dcc1d962f5865

**Comment by ryanbugden** [comment]
<img width="391" alt="image" src="https://github.com/typemytype/outlinerRoboFontExtension/assets/12752088/193ae642-7754-4369-a59f-5c8feed92f7a">
I think I'm on the latest
