### ISSUE TITLE
Traceback with preserveBounds

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/outlinerRoboFontExtension#9]
```
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 88, in sendEvent_
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 539, in action_
  File "outline.py", line 343, in outlineButtonCallback
  File "outline.py", line 57, in calculate
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/objects/glyph.py", line 267, in _get_bounds
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/objects/glyph.py", line 258, in _getContourComponentBounds
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/objects/component.py", line 124, in _get_bounds
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/objects/base.py", line 342, in getRepresentation
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/tools/representations.py", line 92, in componentBoundsRepresentationFactory
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/objects/component.py", line 176, in draw
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/defcon/objects/component.py", line 185, in drawPoints
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/fontTools/pens/pointPen.py", line 264, in addComponent
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/fontTools/pens/basePen.py", line 217, in addComponent
TypeError: 'NoneType' object is not subscriptable
```

Using these settings:
<img width="400" alt="image" src="https://github.com/typemytype/outlinerRoboFontExtension/assets/12752088/1eeed75f-c84f-4dee-8bf0-63c7fb64549c">

**Comment by typemytype** [comment]
should be fixed!!
